USE NOTA_FISCAL_NORMALIZADA;

-- FORMA CLASSICA DE CONSULTAS COMBINADAS 

SELECT NOTA_FISCAL.*, ITEM_NOTA_FISCAL.* 
FROM NOTA_FISCAL, ITEM_NOTA_FISCAL
WHERE NOTA_FISCAL.NRO_NOTA = ITEM_NOTA_FISCAL.NRO_NOTA;

-- podemos definir ALIAS (apelidos) para as tabelas e facilitar a codifição 

SELECT  NF.NRO_NOTA, NF.DT_EMISSAO, NF.VL_TOTAL,
		INF.COD_PRODUTO, P.DESC_PRODUTO,  P.UN_MED,
        INF.QTD_PRODUTO, INF.VL_PRECO,
        INF.VL_TOTAL
FROM 
	NOTA_FISCAL AS NF, 
    ITEM_NOTA_FISCAL AS INF,
    PRODUTO AS P 
WHERE
	NF.NRO_NOTA = INF.NRO_NOTA
    AND INF.COD_PRODUTO = P.COD_PRODUTO
ORDER BY 
		NF.NRO_NOTA DESC, INF.COD_PRODUTO ASC;
        
-- INNER JOIN

SELECT  NF.NRO_NOTA, NF.DT_EMISSAO, NF.VL_TOTAL,
		INF.COD_PRODUTO, P.DESC_PRODUTO,  P.UN_MED,
        INF.QTD_PRODUTO, INF.VL_PRECO,
        INF.VL_TOTAL
FROM 
	NOTA_FISCAL AS NF 
    INNER JOIN
		ITEM_NOTA_FISCAL AS INF ON NF.NRO_NOTA = INF.NRO_NOTA
    INNER JOIN 
			PRODUTO AS P ON INF.COD_PRODUTO = P.COD_PRODUTO
WHERE NF.NRO_NOTA = 4
ORDER BY 
		NF.NRO_NOTA DESC, INF.COD_PRODUTO ASC;
        
        
-- FUNÇOES DE AGREGAÇÃO 
-- CONTANDO E QUANTIFICANDO REGISTROS

-- QUANTAS NOTAS FISCAIS TEM EMITIDAS?

SELECT COUNT(*)
FROM NOTA_FISCAL;

-- NOTAS FISCAIS POR PERIODO 
SELECT COUNT(*) 
FROM NOTA_FISCAL
WHERE DT_EMISSAO > '2025-03-21' AND DT_EMISSAO < '2025-03-25';

SELECT COUNT(*) 
FROM NOTA_FISCAL
WHERE DT_EMISSAO BETWEEN '2025-03-21' AND  '2025-03-25';

-- TOTAL DE NOTAS NO ANO

SELECT COUNT(*)
FROM NOTA_FISCAL 
WHERE YEAR (DT_EMISSAO) = 2025;

-- MAX () -> OBTENDO O CLIENTE QUE MAIS COMPROU DETERMINADO PRODUTO EM UMA UNICA NF

SELECT NF.NM_CLIENTE AS CLIENTE, 
	P.DESC_PRODUTO AS PRODUTO,
	MAX(QTD_PRODUTO) AS QTD
FROM ITEM_NOTA_FISCAL AS INF 
INNER JOIN NOTA_FISCAL AS NF 
	ON INF.NRO_NOTA = NF.NRO_NOTA
INNER JOIN PRODUTO AS P
	ON INF.COD_PRODUTO = P.COD_PRODUTO
-- WHERE INF.COD_PRODUTO = 2
GROUP BY NF.NM_CLIENTE, P.DESC_PRODUTO
ORDER BY CLIENTE, QTD DESC;
        