USE nota_fiscal_normalizada;

DELIMITER $$

CREATE TRIGGER PROMO_CHECK
BEFORE UPDATE ON PRODUTO
FOR EACH ROW 
BEGIN

	DECLARE NOME VARCHAR(265);
    
    SELECT DESC_PRODUTO
    INTO NOME
    FROM PRODUTO
    WHERE COD_PRODUTO = NEW.COD_PRODUTO;
    
    IF NEW.VL_PRODUTO < 100 THEN 
		SET NEW.DESC_PRODUTO =
			CONCAT('PRODUTO', ' ', NOME);
		ELSEIF NEW.VL_PRODUTO >= 100 AND
			NEW.VL_PRODUTO <= 200 THEN
		SET  NEW.DESC_PRODUTO =
			CONCAT('OFERTA ', ' ', NOME);
		END IF;
	END $$
            
UPDATE PRODUTO
SET VL_PRODUTO = 85
WHERE COD_PRODUTO IN (1,2);
    
    
    
    