CREATE DATABASE NOTA_FISCAL_NORMALIZADA;

USE `NOTA_FISCAL_NORMALIZADA`;

CREATE TABLE `NOTA_FISCAL`(
`NRO_NOTA` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`NM_CLIENTE` VARCHAR(256) NOT NULL, 
`END_CLIENTE` VARCHAR(256) NOT NULL, 
`NM_VENDEDOR` VARCHAR(256) NOT NULL, 
`DT_EMISSAO` DATETIME DEFAULT CURRENT_TIMESTAMP,
`VL_TOTAL` FLOAT NOT NULL 

);

CREATE TABLE `PRODUTO` (
	`COD_PRODUTO` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `DESC_PRODUTO` VARCHAR (256) NOT NULL, 
    `UN_MED` CHAR(2) NOT NULL, 
    `VL_PRODUTO` FLOAT NOT NULL
    
 );   
 
 CREATE TABLE `ITEM_NOTA_FISCAL`(
	`NRO_NOTA` INT NOT NULL,
    `COD_PRODUTO` INT NOT NULL,
    `QTD_PRODUTO` INT NOT NULL,
    `VL_PRECO` FLOAT NOT NULL, 
    `VL_TOTAL` FLOAT NOT NULL, 
    PRIMARY KEY (NRO_NOTA, COD_PRODUTO),
    CONSTRAINT FK_NRO_NOTA_NOTA_FISCAL FOREIGN KEY (NRO_NOTA) REFERENCES NOTA_FISCAL (NRO_NOTA),
    CONSTRAINT FK_COD_PRODUTO_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO (COD_PRODUTO)
);

-- produto

INSERT INTO `PRODUTO` (DESC_PRODUTO, UN_MED, VL_PRODUTO) VALUES ('Leite', 'LT', 4.50);
INSERT INTO `PRODUTO` (DESC_PRODUTO, UN_MED, VL_PRODUTO) VALUES ('Desodorante', 'UN', 8.00);
INSERT INTO `PRODUTO` (DESC_PRODUTO, UN_MED, VL_PRODUTO) VALUES ('Salame', 'KG', 40.00);

SELECT * FROM `PRODUTO`;
-- nota fiscal 

INSERT INTO `NOTA_FISCAL` (NM_CLIENTE, END_CLIENTE, NM_VENDEDOR, VL_TOTAL)
VALUE ('Aragorn', 'Terra Media', 'Bilbo', 100.00);

INSERT INTO `NOTA_FISCAL` (NM_CLIENTE, END_CLIENTE, NM_VENDEDOR, VL_TOTAL)
VALUE ('Gandalf', 'Terra Media', 'Frodo', 100.00);

INSERT INTO `NOTA_FISCAL` (NM_CLIENTE, END_CLIENTE, NM_VENDEDOR, VL_TOTAL)
VALUE ('Boromir', 'Mordor', 'Sam', 100.00);

INSERT INTO `NOTA_FISCAL` (NM_CLIENTE, END_CLIENTE, NM_VENDEDOR, VL_TOTAL)
VALUE ('Galadriel', 'Valinor', 'Saruman', 100.00);

SELECT * FROM `NOTA_FISCAL`;

-- Itens da nota

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) 
VALUE (1, 1, 1, 4.50, 4.50);

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) 
VALUE (1, 2, 2, 40.00, 80.00);

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) 
VALUE (1, 3, 10, 100.00, 1000.00);



-- nota 2

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) 
VALUE (2, 3, 33, 33.00, 3000.00);

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) 
VALUE (2, 1, 1, 9.00, 9.00);

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) 
VALUE (2, 2, 2, 80.00, 160.00);


-- nota 3

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) 
VALUE (3, 1, 1, 18.00, 18.00);

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) 
VALUE (3, 2, 2, 160.00, 320.00);

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) 
VALUE (3, 3, 10, 400.00, 4000.00);

-- nota 4

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) 
VALUE (4, 1, 1, 78.00, 98.00);

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) 
VALUE (4, 2, 2, 760.00, 420.00);

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL) 
VALUE (4, 3, 11, 800.00, 6000.00);


SELECT * FROM `ITEM_NOTA_FISCAL`;


SELECT * FROM PRODUTO WHERE COD_PRODUTO=3;

--  UPDATE, ATUALIZANDO DADOS DE COLUNAS EM TABELAS 

UPDATE PRODUTO
SET VL_PRODUTO = 45, DESC_PRODUTO = 'Atualizado', UN_MED = 'CX'
WHERE COD_PRODUTO = 3;
 
 
-- DELETE, EXCLUINDO REGISTRO DE TABELAS 
DELETE FROM PRODUTO 
WHERE COD_PRODUTO = 3;
--  NESTE CASO UMA EXCECAO SERA LANÇADA VIOLAÇÃO DA CONTRAINT QUE AMARRA O PRODUTO AO 
-- ITEM DA NOTA FISCAL, NAO E POSSIVEL EXCLUIR UMA CHAVE PRIMARIA QUE TEM DEPENDENCIAS EM FKs

INSERT INTO PRODUTO (DESC_PRODUTO, UN_MED, VL_PRODUTO)
VALUES('TESTE DELETE','LT', 5.50);

SELECT * FROM PRODUTO;

DELETE FROM PRODUTO WHERE COD_PRODUTO = 4;




    